apiVersion: batch/v1
kind: CronJob
metadata:
  name: date-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: show-date
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes CronJob!
          restartPolicy: OnFailure

