# Invalid 
---
apiVersion: v1
kind: Pod
metadata:
  name: insecure-invalid-pod
spec:
  containers:
  - name: app
    image: nginx
    command: ["sleep", "infinity"]
    securityContext:
      allowPrivilegeEscalation: true

---
# Valid
apiVersion: v1
kind: Pod
metadata:
  name: insecure-valid-pod
spec:
  containers:
  - name: app
    image: nginx
    command: ["sleep", "infinity"]
    securityContext:
      allowPrivilegeEscalation: false
