# Invalid 
---
apiVersion: v1
kind: Pod
metadata:
  name: insecure-invalid-pod
spec:
  containers:
  - name: app
    image: alpine 
    command: ["sleep", "infinity"]
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_ADMIN"]

---
# Valid
apiVersion: v1
kind: Pod
metadata:
  name: insecure-valid-pod
spec:
  containers:
  - name: app
    image: alpine 
    command: ["sleep", "infinity"]
    securityContext:
      capabilities:
        drop: ["ALL"]  # 기본은 다 제거하고
        add: ["CHOWN"]  # 필요한 최소 권한만 추가
