# Invalid 
---
apiVersion: v1
kind: Pod
metadata:
  name: insecure-invalid-pod
spec:
  hostPID: true
  containers:
  - name: app
    image: alpine 
    command: ["sleep", "infinity"]


---
# Valid
apiVersion: v1
kind: Pod
metadata:
  name: insecure-valid-pod
spec:
  hostPID: false
  containers:
  - name: app
    image: alpine 
    command: ["sleep", "infinity"]
