# Invalid 
---
apiVersion: v1
kind: Pod
metadata:
  name: insecure-invalid-pod
spec:
  containers:
  - name: app
    image: alpine 
    securityContext:
      privileged: true
    command: ["sleep", "infinity"]

---
#Valid
apiVersion: v1
kind: Pod
metadata:
  name: insecure-valid-pod
spec:
  containers:
  - name: app
    image: alpine 
    securityContext:
      privileged: false
    command: ["sleep", "infinity"]
