# Invalid 
---
apiVersion: v1
kind: Pod
metadata:
  name: insecure-invalid-pod
spec:
  containers:
  - name: app
    image: alpine 
    securityContext:
      runAsUser: 0
    command: ["sleep", "infinity"]

---
# Valid
apiVersion: v1
kind: Pod
metadata:
  name: insecure-valid-pod
spec:
  containers:
  - name: app
    image: alpine 
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
    command: ["sleep", "infinity"]
